import PageTransition from '@/app/components/PageTransition'
import { AppNavbar } from '@/app/components/navbar'
import { Geist, Paytone_One } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const paytoneOne = Paytone_One({
  variable: "--font-paytone-one",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${paytoneOne.variable} antialiased`}
      >
        <PageTransition>
          <AppNavbar className="" />
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
